changesetIgnorePatterns:
  - tests/**/*.spec.ts

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: ${GITHUB_TOKEN}

npmScopes:
  tdak1509:
    npmRegistryServer: "https://npm.pkg.github.com/"
